version: '3.8'

services:
  akoming-test:
    image: saokiritoni/akoming-test:latest  # 이미지 이름과 태그를 맞게 변경하세요.
    container_name: akoming-test
    ports:
      - "8080:8080"  # 포트 매핑을 설정합니다.
    env_file:
      - /home/ubuntu/.env  # EC2 서버의 .env 파일 경로를 지정합니다.
    restart: unless-stopped
